@startuml
!include style.puml
skinparam ArrowFontStyle plain

box CreateStudentCommand LOGIC_COLOR_T1
participant ":CreateStudentCommand" as command LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManagerStatic MODEL_COLOR
participant "opr:ChildOperation<Student>" as ChildOperation MODEL_COLOR
participant "g:Group" as Group MODEL_COLOR
end box

[-> command : execute()
activate command

command -> ModelManagerStatic : groupChildOperation(path)
activate ModelManagerStatic

create ChildOperation
ModelManagerStatic -> ChildOperation
activate ChildOperation

ChildOperation --> ModelManagerStatic : opr
deactivate ChildOperation

ModelManagerStatic --> command : opr
deactivate ModelManagerStatic

command -> ChildOperation : addChild(id, student)
activate ChildOperation

ChildOperation -> Group : addChild(id, student)
activate Group

Group --> ChildOperation
deactivate Group

ChildOperation --> command
destroy ChildOperation

[<--command
deactivate command
@enduml
