@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Command LOGIC_COLOR_T1
participant ":CreateDeadlineCommand" as CreateDeadlineCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManagerStatic MODEL_COLOR
participant "opr:TaskOperation" as TaskOperation MODEL_COLOR
participant ":Student" as Student MODEL_COLOR
end box

[->  CreateDeadlineCommand : execute()
activate CreateDeadlineCommand

CreateDeadlineCommand -> ModelManagerStatic : taskOperation(path)
activate ModelManagerStatic

create TaskOperation
ModelManagerStatic -> TaskOperation
activate TaskOperation

TaskOperation --> ModelManagerStatic : opr
deactivate TaskOperation

ModelManagerStatic --> CreateDeadlineCommand :opr
deactivate ModelManagerStatic

CreateDeadlineCommand -> TaskOperation : addAllTask(task)
activate TaskOperation

loop for each student in group
    TaskOperation -> Student : addTask(task)
    activate Student


    Student --> TaskOperation
    deactivate Student
end

TaskOperation --> CreateDeadlineCommand

destroy TaskOperation

[<--CreateDeadlineCommand
destroy CreateDeadlineCommand
@enduml
@enduml
