@startuml
title Group 1's Final state

object "<u>:Group</u>" as group1

object "<u>:Student</u>" as student1 {
    name = "ben"
    id = 1212A
}

object "<u>:Student</u>" as student2 {
    name = "jerry"
    id = 2727B
}

object "<u>:Deadline</u>" as deadline1 {
    description = "Assignment 1"
    deadline = 2023-12-12 2359
}

object "<u>:Deadline</u>" as deadline2 {
    description = "Assignment 1"
    deadline = 2023-12-12 2359
}

group1 -down-> student1
group1 -down-> student2
student2 -down-> deadline1
student1 -down-> deadline2
@enduml
