@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class ProfBookStorageManager

package "ProfBook Storage" #F4F6F6{
Class "<<interface>>\nProfBookStorage" as ProfBookStorage
Class JsonSerializableProfBook
Class JsonAdaptedStudent
Class JsonProfBookStorage
Class JsonAdaptedRoot
Class JsonAdaptedGroup
Class "{abstract}\nJsonAdaptedTask" as JsonAdaptedTask
Class JsonAdaptedDeadline
Class JsonAdaptedToDo
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

ProfBookStorageManager .up.|> Storage
ProfBookStorageManager -up-> "1" UserPrefsStorage
ProfBookStorageManager -up-> "1" ProfBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ProfBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonProfBookStorage .up.|> ProfBookStorage
JsonProfBookStorage ..> JsonSerializableProfBook
JsonSerializableProfBook --> "1" JsonAdaptedRoot
JsonAdaptedRoot --> "*" JsonAdaptedGroup
JsonAdaptedGroup -right-> "*" JsonAdaptedStudent
JsonAdaptedGroup --> "*" JsonAdaptedTask
JsonAdaptedStudent --> "*" JsonAdaptedTask
JsonAdaptedDeadline -up-|> JsonAdaptedTask
JsonAdaptedToDo -up-|> JsonAdaptedTask
@enduml
