@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class ProfBookStorageManager

package "ProfBook Storage" #F4F6F6{
Class "<<interface>>\nProfBookStorage" as ProfBookStorage
Class JsonSerializableProfBook
Class JsonAdaptedStudent
Class JsonAdaptedTag
Class JsonProfBookStorage
Class JsonAdaptedXYZ
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> ProfBookStorageManager

ProfBookStorageManager -down-|> UserPrefsStorage
ProfBookStorageManager -right-|> ProfBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonProfBookStorage .up.|> ProfBookStorage
JsonProfBookStorage ..> JsonSerializableProfBook
JsonSerializableProfBook --> "*" JsonAdaptedStudent
JsonSerializableProfBook --> "*" JsonAdaptedXYZ
JsonAdaptedStudent --> "*" JsonAdaptedTag

@enduml
